# Python para Inteligência Artificial
---

**Professor: Dr. Daniel Neri Cardoso**

## Módulo 4 — pandas

### Lista de exercícios


**Aluna: Angelina de Meiras Ottoni**

# =========================================
# Exercise 1 — Criando `DataFrames`
# =========================================

In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 631.6 kB/s eta 0:00:00a 0:00:01
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/angel-ottoni/amo_projects/ppgmcs/python-for-ai/.my_venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/angel-ottoni/amo_projects/ppgmcs/python-for-ai/.my_venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 5.0 MB/s eta 0:00:0000:0100:01
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 4.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [3]:
data = {
    'Name': ['Ana', 'João', 'Clara'],
    'Age': [28, 35, 22],
    'Salary': [3500.00, 4200.50, 2800.00]
}

In [5]:
df_test = pd.DataFrame(data)
display(df_test)

    Name  Age  Salary
0    Ana   28  3500.0
1   João   35  4200.5
2  Clara   22  2800.0

In [8]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 204.0 bytes

# =========================================
# Exercise 2 — Comandos de Inspeção
# =========================================

In [6]:
# First 2 rows
df_test.head(2)

   Name  Age  Salary
0   Ana   28  3500.0
1  João   35  4200.5

In [7]:
# Statistical summary
df_test.describe()

             Age       Salary
count   3.000000     3.000000
mean   28.333333  3500.166667
std     6.506407   700.250015
min    22.000000  2800.000000
25%    25.000000  3150.000000
50%    28.000000  3500.000000
75%    31.500000  3850.250000
max    35.000000  4200.500000

# =========================================
# Exercise 3 — Indexação
# =========================================

In [ ]:
# Salary of João (row 1, column 2)
print(f"R${df_test.iloc[1, 2]:.2f}")

R$4200.50

In [14]:
# Age of Clara using label
df_test.loc[df_test['Name'] == 'Clara', 'Age']

2    22
Name: Age, dtype: int64

# =========================================
# Exercise 4 — Carregamento de Dados
# =========================================

In [12]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 1.1 MB/s eta 0:00:0000:0100:01m
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [15]:
import openpyxl as open

In [74]:
df = pd.read_excel('data/raw/funcionarios.xlsx')

In [59]:
display(df.head())

              Nome  Idade   Salario Departamento
0       Joao Souza   27.0   3885.53       Vendas
1         Ana Lima   20.0   5985.67           RH
2   Helena Pereira   31.0  13986.53           TI
3    Eduardo Souza   44.0   7478.16           TI
4  Maria Fernandes   37.0   6706.45       Vendas

In [60]:
df.shape

(250, 4)

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nome          250 non-null    str
 1   Idade         225 non-null    float64
 2   Salario       250 non-null    float64
 3   Departamento  250 non-null    str
dtypes: float64(2), str(2)
memory usage: 7.9 KB

# =========================================
# Exercise 5 — Detecção de Dados Faltantes
# =========================================

In [62]:
df.isnull().sum()

Nome             0
Idade           25
Salario          0
Departamento     0
dtype: int64

In [63]:
df['Idade'].unique()

array([27., 20., 31., 44., 37., 23., 39., 26., 36., 24., 41., 46., nan,
       21., 40., 65., 45., 42., 43., 33., 30., 58., 18., 19., 28., 35.,
       56., 32., 53., 22., 48., 34., 25., 51., 49., 47., 29., 38., 50.,
       57., 54.])

In [64]:
df['Idade'].value_counts().head()

Idade
27.0    12
37.0    12
36.0    12
28.0    10
41.0     9
Name: count, dtype: int64

# =========================================
# Exercise 6 — Tratamento de Erros
# =========================================

In [65]:
# Mean age
mean_age = df['Idade'].mean()

print(mean_age)

35.61333333333334

In [ ]:
# Fill missing values with mean (imputation)
df['Idade'] = df['Idade'].fillna(mean_age)

In [67]:
# Inspect values before rounding
df['Idade'].unique()

array([27.        , 20.        , 31.        , 44.        , 37.        ,
       23.        , 39.        , 26.        , 36.        , 24.        ,
       41.        , 46.        , 35.61333333, 21.        , 40.        ,
       65.        , 45.        , 42.        , 43.        , 33.        ,
       30.        , 58.        , 18.        , 19.        , 28.        ,
       35.        , 56.        , 32.        , 53.        , 22.        ,
       48.        , 34.        , 25.        , 51.        , 49.        ,
       47.        , 29.        , 38.        , 50.        , 57.        ,
       54.        ])

In [68]:
df['Idade'].value_counts().head()

Idade
35.613333    25
27.000000    12
37.000000    12
36.000000    12
28.000000    10
Name: count, dtype: int64

In [ ]:
# Inspect distribution after imputation
df.describe()

            Idade       Salario
count  250.000000    250.000000
mean    35.613333   7272.971880
std      9.166326   3026.235709
min     18.000000   2184.180000
25%     29.000000   5025.972500
50%     35.613333   6757.065000
75%     41.000000   9160.692500
max     65.000000  14974.620000

In [ ]:
# Round and convert to integer to preserve semantic meaning of age
df['Idade'] = df['Idade'].round().astype(int)

In [71]:
df['Idade'].unique()

array([27, 20, 31, 44, 37, 23, 39, 26, 36, 24, 41, 46, 21, 40, 65, 45, 42,
       43, 33, 30, 58, 18, 19, 28, 35, 56, 32, 53, 22, 48, 34, 25, 51, 49,
       47, 29, 38, 50, 57, 54])

In [72]:
df['Idade'].value_counts().head()

Idade
36    37
27    12
37    12
28    10
41     9
Name: count, dtype: int64

In [73]:
df.describe()

            Idade       Salario
count  250.000000    250.000000
mean    35.652000   7272.971880
std      9.167063   3026.235709
min     18.000000   2184.180000
25%     29.000000   5025.972500
50%     36.000000   6757.065000
75%     41.000000   9160.692500
max     65.000000  14974.620000

⚠️ **Observação sobre precisão dos dados**

Embora neste caso tenha sido realizado o arredondamento da variável `Idade`, é importante destacar que essa decisão depende do contexto dos dados.

*Caso os dados reais apresentem valores contínuos (com casas decimais), essa precisão deve ser preservada, evitando arredondamentos que possam levar à perda de informação ou distorção da distribuição original.*

# =========================================
# Exercise 7 — Seleção Lógica
# =========================================

In [53]:
df_ti_senior = df[(df['Departamento'] == 'TI') & (df['Salario'] > 8000)]

# Count how many
len(df_ti_senior)

59

# =========================================
# Exercise 8 — Criação de Colunas
# =========================================

In [54]:
df['Bonus'] = df['Salario'] * 0.10

In [55]:
df.head()

              Nome  Idade   Salario Departamento     Bonus
0       Joao Souza     27   3885.53       Vendas   388.553
1         Ana Lima     20   5985.67           RH   598.567
2   Helena Pereira     31  13986.53           TI  1398.653
3    Eduardo Souza     44   7478.16           TI   747.816
4  Maria Fernandes     37   6706.45       Vendas   670.645

# =========================================
# Exercise 9 — Estatística Descritiva
# =========================================

In [56]:
df['Departamento'].value_counts()

Departamento
Vendas    124
TI         85
RH         41
Name: count, dtype: int64

# =========================================
# Exercise 10 — Exportação
# =========================================

In [ ]:
df.to_excel('data/processed/relatorio_final.xlsx', index=False)